apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark-client
  template:
    metadata:
      labels:
        app: benchmark-client
    spec:
      imagePullSecrets:
      - name: private-reg-cred
      containers:
      - name: benchmark-client
        image: quay.io/mpaulgreen/benchmark-client:11
        env:
        - name: URL
          value: "http://mongodb-quickstart-mongodb.apps.mpkogito.pkgo.p1.openshiftapps.com/"
        - name: WORKER_POOL_SIZE
          value: "100"
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: benchmark-client
spec:
  selector:
    app: benchmark-client
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090