apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-quickstart
spec:
  replicas: 10
  selector:
    matchLabels:
      app: mongodb-quickstart
  template:
    metadata:
      labels:
        app: mongodb-quickstart
    spec:
      imagePullSecrets:
      - name: private-reg-cred
      containers:
      - name: mongodb-quickstart
        image: quay.io/mpaulgreen/mongodb-quickstart:21
        env:
        - name: MIN_POOL
          value: "10"
        - name: MAX_POOL
          value: "10"
        - name: WORKER_POOL_SIZE
          value: "10"
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-quickstart
spec:
  selector:
    app: mongodb-quickstart
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9090